"""Database tests for the Companies table / migration 011.

These exercise guarantees that only a real PostgreSQL can provide:

* a row inserts successfully and ``id`` is auto-generated (IDENTITY),
* duplicate Commercial Registration numbers are rejected (UNIQUE),
* duplicate VAT numbers are rejected (UNIQUE),
* required fields cannot be NULL,
* Arabic / English addresses accept long text,
* whitespace is trimmed on save and the ``updated_at`` trigger fires,
* the migration upgrades and downgrades successfully.

Isolation: every test runs inside a throwaway schema (``co_test_<n>``) created in
setup and ``DROP SCHEMA ... CASCADE``-d in teardown. All objects are created
*inside* that schema via ``search_path``, so nothing in ``public`` (real app data)
is created, altered, or dropped. If no database is reachable the whole module is
skipped.
"""

from __future__ import annotations

import os
from pathlib import Path

import pytest

from app.database.db import Database
from app.models.company import COMPANIES_SCHEMA_SQL

# A per-test-run counter for unique schema names (Date/random are avoided so the
# suite stays deterministic across reruns within a session).
_SCHEMA_SEQ = iter(range(1, 1_000_000))

_MIGRATIONS_DIR = (
    Path(__file__).resolve().parents[2] / "app" / "database" / "migrations"
)
_UPGRADE_SQL = _MIGRATIONS_DIR / "011_create_companies_schema.sql"
_DOWNGRADE_SQL = _MIGRATIONS_DIR / "011_downgrade_companies_schema.sql"


def _try_connect() -> Database | None:
    try:
        db = Database()
        db.execute("SELECT 1")
        return db
    except Exception:
        return None


_probe = _try_connect()
pytestmark = pytest.mark.skipif(
    _probe is None,
    reason="No PostgreSQL reachable (set DB_* env / .env to run company DB tests).",
)


def _bound_db(schema: str) -> Database:
    """A fresh Database whose connection has search_path set to ``schema, public``."""
    db = Database()
    db.execute(f'SET search_path TO "{schema}", public')
    return db


def _insert(db: Database, **cols):
    """Insert a companies row (defaults for the required fields) and RETURNING *."""
    values = {
        "name_ar": "شركة الاختبار",
        "name_en": None,
        "commercial_registration": "CR-0001",
        "vat_number": "VAT-0001",
        "address_ar": None,
        "address_en": None,
    }
    values.update(cols)
    keys = list(values)
    placeholders = ", ".join(["%s"] * len(keys))
    sql = (
        f"INSERT INTO companies ({', '.join(keys)}) "
        f"VALUES ({placeholders}) RETURNING *"
    )
    return db.fetch_one(sql, [values[k] for k in keys])


@pytest.fixture()
def schema():
    name = f"co_test_{next(_SCHEMA_SEQ)}_{os.getpid()}"
    admin = Database()
    admin.execute(f'CREATE SCHEMA "{name}"')
    try:
        yield name
    finally:
        admin.execute(f'DROP SCHEMA IF EXISTS "{name}" CASCADE')


@pytest.fixture()
def db(schema):
    """A DB bound to a throwaway schema with the companies table provisioned."""
    conn = _bound_db(schema)
    conn.execute_script(COMPANIES_SCHEMA_SQL)
    return conn


# --- insert + auto-generated id ---------------------------------------------

def test_insert_succeeds_and_id_is_autogenerated(db):
    row = _insert(db, name_ar="شركة النور", commercial_registration="1010", vat_number="3001")
    assert isinstance(row["id"], int)
    assert row["id"] >= 1
    assert row["name_ar"] == "شركة النور"
    # registration / VAT are stored verbatim as strings (leading zeros preserved).
    assert row["commercial_registration"] == "1010"
    assert row["vat_number"] == "3001"
    assert row["created_at"] is not None
    assert row["updated_at"] is not None


def test_ids_increment_automatically(db):
    a = _insert(db, commercial_registration="CR-A", vat_number="VAT-A")
    b = _insert(db, commercial_registration="CR-B", vat_number="VAT-B")
    assert b["id"] > a["id"]


def test_leading_zeros_preserved(db):
    row = _insert(db, commercial_registration="0007", vat_number="00042")
    assert row["commercial_registration"] == "0007"
    assert row["vat_number"] == "00042"


# --- duplicate rejection (UNIQUE indexes) -----------------------------------

def test_duplicate_commercial_registration_rejected(db):
    import psycopg

    _insert(db, commercial_registration="CR-DUP", vat_number="VAT-1")
    with pytest.raises(psycopg.errors.UniqueViolation):
        _insert(db, commercial_registration="CR-DUP", vat_number="VAT-2")


def test_duplicate_vat_number_rejected(db):
    import psycopg

    _insert(db, commercial_registration="CR-1", vat_number="VAT-DUP")
    with pytest.raises(psycopg.errors.UniqueViolation):
        _insert(db, commercial_registration="CR-2", vat_number="VAT-DUP")


# --- required fields cannot be NULL -----------------------------------------

@pytest.mark.parametrize("field", ["name_ar", "commercial_registration", "vat_number"])
def test_required_fields_not_null(db, field):
    import psycopg

    with pytest.raises(psycopg.errors.NotNullViolation):
        _insert(db, **{field: None})


# --- required text may not be blank (trigger trims, CHECK rejects) ----------

@pytest.mark.parametrize("field", ["name_ar", "commercial_registration", "vat_number"])
def test_required_fields_not_blank(db, field):
    import psycopg

    with pytest.raises(psycopg.errors.CheckViolation):
        _insert(db, **{field: "   "})


# --- optional Arabic / English addresses accept long text -------------------

def test_addresses_accept_long_text(db):
    long_ar = "ش" * 5000
    long_en = "A" * 5000
    row = _insert(
        db,
        commercial_registration="CR-LONG",
        vat_number="VAT-LONG",
        address_ar=long_ar,
        address_en=long_en,
    )
    assert row["address_ar"] == long_ar
    assert row["address_en"] == long_en
    assert len(row["address_ar"]) == 5000


# --- normalisation trigger: trims + blank optional -> NULL, updated_at ------

def test_whitespace_is_trimmed_on_insert(db):
    row = _insert(
        db,
        name_ar="  شركة مبطنة  ",
        name_en="  Padded Co  ",
        commercial_registration="  CR-TRIM  ",
        vat_number="  VAT-TRIM  ",
        address_ar="   ",  # whitespace-only optional -> NULL
    )
    assert row["name_ar"] == "شركة مبطنة"
    assert row["name_en"] == "Padded Co"
    assert row["commercial_registration"] == "CR-TRIM"
    assert row["vat_number"] == "VAT-TRIM"
    assert row["address_ar"] is None


def test_update_bumps_updated_at(db):
    row = _insert(db, commercial_registration="CR-U", vat_number="VAT-U")
    updated = db.fetch_one(
        "UPDATE companies SET name_ar = %s WHERE id = %s RETURNING *",
        ["اسم جديد", row["id"]],
    )
    assert updated["name_ar"] == "اسم جديد"
    assert updated["updated_at"] >= row["updated_at"]


# --- migration upgrades and downgrades successfully -------------------------

def test_migration_upgrade_then_downgrade(schema):
    conn = _bound_db(schema)
    reg = f"SELECT to_regclass('\"{schema}\".companies') AS t"

    # Fresh schema: table not present yet.
    assert conn.fetch_one(reg)["t"] is None

    conn.execute_script(_UPGRADE_SQL.read_text(encoding="utf-8"))
    assert conn.fetch_one(reg)["t"] is not None
    # Table is usable after upgrade.
    _insert(conn, commercial_registration="CR-MIG", vat_number="VAT-MIG")

    conn.execute_script(_DOWNGRADE_SQL.read_text(encoding="utf-8"))
    assert conn.fetch_one(reg)["t"] is None


def test_migration_upgrade_is_idempotent(schema):
    conn = _bound_db(schema)
    up = _UPGRADE_SQL.read_text(encoding="utf-8")
    conn.execute_script(up)
    conn.execute_script(up)  # second run must not raise
    reg = f"SELECT to_regclass('\"{schema}\".companies') AS t"
    assert conn.fetch_one(reg)["t"] is not None
