-- 015a_create_sales_invoice_schema.sql
-- Creates the Saudi (ZATCA) sales-invoice tables:
--   sales_invoices, sales_invoice_lines, sales_invoice_zatca_data,
--   sales_invoice_zatca_submissions, sales_invoice_audit_logs
--
-- These tables were originally introduced by direct DDL (no numbered migration),
-- so this file captures their schema so a fresh database is complete. It runs
-- BEFORE 016 (which only drops a NOT NULL on sales_invoice_lines.product_id).
--
-- Generated from the reference schema with `pg_dump --schema-only` (no data).
-- Depends on: customers (001), app_users (004), products (009), companies (011).

SET search_path = public;

-- Shared trigger function that stamps updated_at on UPDATE. Defined here because
-- the sales-invoice triggers below use it (CREATE OR REPLACE is idempotent).
CREATE OR REPLACE FUNCTION public.sales_set_updated_at()
    RETURNS trigger
    LANGUAGE plpgsql
AS $function$
BEGIN
    NEW.updated_at = now();
    RETURN NEW;
END;
$function$;

--
--

--
-- Name: sales_invoice_audit_logs; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.sales_invoice_audit_logs (
    id bigint NOT NULL,
    invoice_id bigint,
    invoice_number_snapshot character varying(100),
    seller_company_id_snapshot bigint,
    action character varying(50) NOT NULL,
    old_status character varying(30),
    new_status character varying(30),
    performed_by integer,
    batch_id uuid,
    details jsonb,
    previous_log_hash text,
    log_hash text,
    performed_at timestamp with time zone DEFAULT now() NOT NULL
);

--
-- Name: sales_invoice_audit_logs_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_invoice_audit_logs ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_invoice_audit_logs_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: sales_invoice_lines; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.sales_invoice_lines (
    id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    line_number integer NOT NULL,
    product_id integer,
    product_code_snapshot character varying(100) NOT NULL,
    product_name_snapshot character varying(255) NOT NULL,
    unit_code character varying(20) DEFAULT 'PCE'::character varying NOT NULL,
    quantity numeric(18,6) NOT NULL,
    unit_price numeric(18,6) NOT NULL,
    line_amount_before_vat numeric(18,2) NOT NULL,
    vat_category_code character varying(10) DEFAULT 'S'::character varying NOT NULL,
    vat_rate numeric(5,2) DEFAULT 15.00 NOT NULL,
    vat_amount numeric(18,2) NOT NULL,
    line_total_including_vat numeric(18,2) NOT NULL,
    tax_exemption_reason_code character varying(100),
    tax_exemption_reason text,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_sales_invoice_lines_line_amount_before_vat_nonnegative CHECK ((line_amount_before_vat >= (0)::numeric)),
    CONSTRAINT ck_sales_invoice_lines_line_number_positive CHECK ((line_number > 0)),
    CONSTRAINT ck_sales_invoice_lines_line_total_including_vat_nonnegative CHECK ((line_total_including_vat >= (0)::numeric)),
    CONSTRAINT ck_sales_invoice_lines_line_total_matches_components CHECK ((line_total_including_vat = (line_amount_before_vat + vat_amount))),
    CONSTRAINT ck_sales_invoice_lines_quantity_positive CHECK ((quantity > (0)::numeric)),
    CONSTRAINT ck_sales_invoice_lines_unit_price_nonnegative CHECK ((unit_price >= (0)::numeric)),
    CONSTRAINT ck_sales_invoice_lines_vat_amount_nonnegative CHECK ((vat_amount >= (0)::numeric)),
    CONSTRAINT ck_sales_invoice_lines_vat_rate_nonnegative CHECK ((vat_rate >= (0)::numeric))
);

--
-- Name: sales_invoice_lines_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_invoice_lines ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_invoice_lines_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: sales_invoice_zatca_data; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.sales_invoice_zatca_data (
    invoice_id bigint NOT NULL,
    device_id bigint,
    uuid uuid,
    invoice_counter_value bigint,
    previous_invoice_hash text,
    invoice_hash text,
    cryptographic_stamp text,
    public_key_snapshot text,
    digital_signature text,
    qr_code_base64 text,
    generated_xml bytea,
    cleared_xml bytea,
    xml_file_name character varying(500),
    xml_file_path text,
    schema_version character varying(30),
    integration_operation character varying(20),
    integration_status character varying(30) DEFAULT 'not_generated'::character varying NOT NULL,
    zatca_request_id character varying(255),
    zatca_response jsonb,
    validation_warnings jsonb,
    validation_errors jsonb,
    xml_generated_at timestamp with time zone,
    submitted_at timestamp with time zone,
    accepted_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_sales_invoice_zatca_data_integration_operation_valid CHECK (((integration_operation IS NULL) OR ((integration_operation)::text = ANY ((ARRAY['clearance'::character varying, 'reporting'::character varying])::text[])))),
    CONSTRAINT ck_sales_invoice_zatca_data_integration_status_valid CHECK (((integration_status)::text = ANY ((ARRAY['not_generated'::character varying, 'generated'::character varying, 'pending'::character varying, 'cleared'::character varying, 'reported'::character varying, 'warning'::character varying, 'rejected'::character varying, 'failed'::character varying])::text[])))
);

--
-- Name: sales_invoice_zatca_submissions; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.sales_invoice_zatca_submissions (
    id bigint NOT NULL,
    invoice_id bigint NOT NULL,
    operation character varying(20) NOT NULL,
    attempt_number integer NOT NULL,
    request_id character varying(255),
    request_payload_hash text,
    http_status_code integer,
    request_metadata jsonb,
    response_payload jsonb,
    warnings jsonb,
    errors jsonb,
    is_success boolean DEFAULT false NOT NULL,
    requested_at timestamp with time zone NOT NULL,
    responded_at timestamp with time zone,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    CONSTRAINT ck_sales_invoice_zatca_submissions_attempt_number_positive CHECK ((attempt_number > 0)),
    CONSTRAINT ck_sales_invoice_zatca_submissions_operation_valid CHECK (((operation)::text = ANY ((ARRAY['clearance'::character varying, 'reporting'::character varying, 'compliance'::character varying])::text[])))
);

--
-- Name: sales_invoice_zatca_submissions_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_invoice_zatca_submissions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_invoice_zatca_submissions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: sales_invoices; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE IF NOT EXISTS public.sales_invoices (
    id bigint NOT NULL,
    invoice_number character varying(100) NOT NULL,
    issue_datetime timestamp with time zone DEFAULT now() NOT NULL,
    seller_company_id integer NOT NULL,
    seller_name_ar_snapshot character varying(255) NOT NULL,
    seller_name_en_snapshot character varying(255),
    seller_vat_number_snapshot character varying(15) NOT NULL,
    customer_id integer NOT NULL,
    customer_name_snapshot character varying(255) NOT NULL,
    customer_vat_number_snapshot character varying(15),
    customer_address_snapshot text,
    payment_type character varying(20) NOT NULL,
    notes text,
    invoice_currency_code character(3) DEFAULT 'SAR'::bpchar NOT NULL,
    tax_currency_code character(3) DEFAULT 'SAR'::bpchar NOT NULL,
    subtotal_before_vat numeric(18,2) DEFAULT 0 NOT NULL,
    vat_total numeric(18,2) DEFAULT 0 NOT NULL,
    total_including_vat numeric(18,2) DEFAULT 0 NOT NULL,
    document_status character varying(30) DEFAULT 'draft'::character varying NOT NULL,
    approved_at timestamp with time zone,
    approved_by integer,
    created_by integer,
    updated_by integer,
    created_at timestamp with time zone DEFAULT now() NOT NULL,
    updated_at timestamp with time zone DEFAULT now() NOT NULL,
    row_version integer DEFAULT 1 NOT NULL,
    CONSTRAINT ck_sales_invoices_document_status_valid CHECK (((document_status)::text = ANY ((ARRAY['draft'::character varying, 'approved'::character varying])::text[]))),
    CONSTRAINT ck_sales_invoices_invoice_number_not_blank CHECK ((char_length(btrim((invoice_number)::text)) > 0)),
    CONSTRAINT ck_sales_invoices_payment_type_valid CHECK (((payment_type)::text = ANY ((ARRAY['cash'::character varying, 'credit'::character varying])::text[]))),
    CONSTRAINT ck_sales_invoices_subtotal_before_vat_nonnegative CHECK ((subtotal_before_vat >= (0)::numeric)),
    CONSTRAINT ck_sales_invoices_total_including_vat_nonnegative CHECK ((total_including_vat >= (0)::numeric)),
    CONSTRAINT ck_sales_invoices_total_matches_components CHECK ((total_including_vat = (subtotal_before_vat + vat_total))),
    CONSTRAINT ck_sales_invoices_vat_total_nonnegative CHECK ((vat_total >= (0)::numeric))
);

--
-- Name: sales_invoices_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.sales_invoices ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.sales_invoices_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

--
-- Name: sales_invoice_audit_logs pk_sales_invoice_audit_logs; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_audit_logs
    ADD CONSTRAINT pk_sales_invoice_audit_logs PRIMARY KEY (id);

--
-- Name: sales_invoice_lines pk_sales_invoice_lines; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_lines
    ADD CONSTRAINT pk_sales_invoice_lines PRIMARY KEY (id);

--
-- Name: sales_invoice_zatca_data pk_sales_invoice_zatca_data; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_zatca_data
    ADD CONSTRAINT pk_sales_invoice_zatca_data PRIMARY KEY (invoice_id);

--
-- Name: sales_invoice_zatca_submissions pk_sales_invoice_zatca_submissions; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_zatca_submissions
    ADD CONSTRAINT pk_sales_invoice_zatca_submissions PRIMARY KEY (id);

--
-- Name: sales_invoices pk_sales_invoices; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoices
    ADD CONSTRAINT pk_sales_invoices PRIMARY KEY (id);

--
-- Name: sales_invoice_lines uq_sales_invoice_lines_invoice_line; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_lines
    ADD CONSTRAINT uq_sales_invoice_lines_invoice_line UNIQUE (invoice_id, line_number);

--
-- Name: sales_invoice_zatca_data uq_sales_invoice_zatca_data_uuid; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_zatca_data
    ADD CONSTRAINT uq_sales_invoice_zatca_data_uuid UNIQUE (uuid);

--
-- Name: sales_invoice_zatca_submissions uq_sales_invoice_zatca_submissions_attempt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_zatca_submissions
    ADD CONSTRAINT uq_sales_invoice_zatca_submissions_attempt UNIQUE (invoice_id, operation, attempt_number);

--
-- Name: sales_invoices uq_sales_invoices_company_number; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoices
    ADD CONSTRAINT uq_sales_invoices_company_number UNIQUE (seller_company_id, invoice_number);

--
-- Name: ix_sales_invoice_audit_logs_action; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_audit_logs_action ON public.sales_invoice_audit_logs USING btree (action);

--
-- Name: ix_sales_invoice_audit_logs_batch_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_audit_logs_batch_id ON public.sales_invoice_audit_logs USING btree (batch_id);

--
-- Name: ix_sales_invoice_audit_logs_invoice_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_audit_logs_invoice_id ON public.sales_invoice_audit_logs USING btree (invoice_id);

--
-- Name: ix_sales_invoice_audit_logs_performed_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_audit_logs_performed_at ON public.sales_invoice_audit_logs USING btree (performed_at);

--
-- Name: ix_sales_invoice_audit_logs_performed_by; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_audit_logs_performed_by ON public.sales_invoice_audit_logs USING btree (performed_by);

--
-- Name: ix_sales_invoice_lines_invoice_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_lines_invoice_id ON public.sales_invoice_lines USING btree (invoice_id);

--
-- Name: ix_sales_invoice_lines_product_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_lines_product_id ON public.sales_invoice_lines USING btree (product_id);

--
-- Name: ix_sales_invoice_zatca_data_device_counter; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_zatca_data_device_counter ON public.sales_invoice_zatca_data USING btree (device_id, invoice_counter_value);

--
-- Name: ix_sales_invoice_zatca_data_integration_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_zatca_data_integration_status ON public.sales_invoice_zatca_data USING btree (integration_status);

--
-- Name: ix_sales_invoice_zatca_data_invoice_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_zatca_data_invoice_hash ON public.sales_invoice_zatca_data USING btree (invoice_hash);

--
-- Name: ix_sales_invoice_zatca_data_submitted_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_zatca_data_submitted_at ON public.sales_invoice_zatca_data USING btree (submitted_at);

--
-- Name: ix_sales_invoice_zatca_submissions_invoice_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_zatca_submissions_invoice_id ON public.sales_invoice_zatca_submissions USING btree (invoice_id);

--
-- Name: ix_sales_invoice_zatca_submissions_is_success; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_zatca_submissions_is_success ON public.sales_invoice_zatca_submissions USING btree (is_success);

--
-- Name: ix_sales_invoice_zatca_submissions_operation; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_zatca_submissions_operation ON public.sales_invoice_zatca_submissions USING btree (operation);

--
-- Name: ix_sales_invoice_zatca_submissions_requested_at; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoice_zatca_submissions_requested_at ON public.sales_invoice_zatca_submissions USING btree (requested_at);

--
-- Name: ix_sales_invoices_company_status_issued; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoices_company_status_issued ON public.sales_invoices USING btree (seller_company_id, document_status, issue_datetime);

--
-- Name: ix_sales_invoices_customer_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoices_customer_id ON public.sales_invoices USING btree (customer_id);

--
-- Name: ix_sales_invoices_document_status; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoices_document_status ON public.sales_invoices USING btree (document_status);

--
-- Name: ix_sales_invoices_issue_datetime; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoices_issue_datetime ON public.sales_invoices USING btree (issue_datetime);

--
-- Name: ix_sales_invoices_seller_company_id; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX ix_sales_invoices_seller_company_id ON public.sales_invoices USING btree (seller_company_id);

--
-- Name: uq_sales_invoice_audit_logs_log_hash; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_sales_invoice_audit_logs_log_hash ON public.sales_invoice_audit_logs USING btree (log_hash) WHERE (log_hash IS NOT NULL);

--
-- Name: uq_sales_invoice_zatca_device_counter; Type: INDEX; Schema: public; Owner: -
--

CREATE UNIQUE INDEX uq_sales_invoice_zatca_device_counter ON public.sales_invoice_zatca_data USING btree (device_id, invoice_counter_value) WHERE ((device_id IS NOT NULL) AND (invoice_counter_value IS NOT NULL));

--
-- Name: sales_invoice_lines trg_sales_invoice_lines_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_sales_invoice_lines_updated_at BEFORE UPDATE ON public.sales_invoice_lines FOR EACH ROW EXECUTE FUNCTION public.sales_set_updated_at();

--
-- Name: sales_invoice_zatca_data trg_sales_invoice_zatca_data_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_sales_invoice_zatca_data_updated_at BEFORE UPDATE ON public.sales_invoice_zatca_data FOR EACH ROW EXECUTE FUNCTION public.sales_set_updated_at();

--
-- Name: sales_invoices trg_sales_invoices_updated_at; Type: TRIGGER; Schema: public; Owner: -
--

CREATE TRIGGER trg_sales_invoices_updated_at BEFORE UPDATE ON public.sales_invoices FOR EACH ROW EXECUTE FUNCTION public.sales_set_updated_at();

--
-- Name: sales_invoice_audit_logs fk_sales_invoice_audit_logs_invoice_id_sales_invoices; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_audit_logs
    ADD CONSTRAINT fk_sales_invoice_audit_logs_invoice_id_sales_invoices FOREIGN KEY (invoice_id) REFERENCES public.sales_invoices(id) ON DELETE SET NULL;

--
-- Name: sales_invoice_audit_logs fk_sales_invoice_audit_logs_performed_by_app_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_audit_logs
    ADD CONSTRAINT fk_sales_invoice_audit_logs_performed_by_app_users FOREIGN KEY (performed_by) REFERENCES public.app_users(id) ON DELETE SET NULL;

--
-- Name: sales_invoice_lines fk_sales_invoice_lines_invoice_id_sales_invoices; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_lines
    ADD CONSTRAINT fk_sales_invoice_lines_invoice_id_sales_invoices FOREIGN KEY (invoice_id) REFERENCES public.sales_invoices(id) ON DELETE CASCADE;

--
-- Name: sales_invoice_lines fk_sales_invoice_lines_product_id_products; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_lines
    ADD CONSTRAINT fk_sales_invoice_lines_product_id_products FOREIGN KEY (product_id) REFERENCES public.products(id) ON UPDATE CASCADE ON DELETE RESTRICT;

--
-- Name: sales_invoice_zatca_data fk_sales_invoice_zatca_data_invoice_id_sales_invoices; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_zatca_data
    ADD CONSTRAINT fk_sales_invoice_zatca_data_invoice_id_sales_invoices FOREIGN KEY (invoice_id) REFERENCES public.sales_invoices(id) ON DELETE CASCADE;

--
-- Name: sales_invoice_zatca_submissions fk_sales_invoice_zatca_submissions_invoice_id_sales_invoices; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoice_zatca_submissions
    ADD CONSTRAINT fk_sales_invoice_zatca_submissions_invoice_id_sales_invoices FOREIGN KEY (invoice_id) REFERENCES public.sales_invoices(id) ON DELETE CASCADE;

--
-- Name: sales_invoices fk_sales_invoices_approved_by_app_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoices
    ADD CONSTRAINT fk_sales_invoices_approved_by_app_users FOREIGN KEY (approved_by) REFERENCES public.app_users(id) ON DELETE RESTRICT;

--
-- Name: sales_invoices fk_sales_invoices_created_by_app_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoices
    ADD CONSTRAINT fk_sales_invoices_created_by_app_users FOREIGN KEY (created_by) REFERENCES public.app_users(id);

--
-- Name: sales_invoices fk_sales_invoices_customer_id_customers; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoices
    ADD CONSTRAINT fk_sales_invoices_customer_id_customers FOREIGN KEY (customer_id) REFERENCES public.customers(customer_id) ON UPDATE CASCADE ON DELETE RESTRICT;

--
-- Name: sales_invoices fk_sales_invoices_seller_company_id_companies; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoices
    ADD CONSTRAINT fk_sales_invoices_seller_company_id_companies FOREIGN KEY (seller_company_id) REFERENCES public.companies(id) ON UPDATE CASCADE ON DELETE RESTRICT;

--
-- Name: sales_invoices fk_sales_invoices_updated_by_app_users; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sales_invoices
    ADD CONSTRAINT fk_sales_invoices_updated_by_app_users FOREIGN KEY (updated_by) REFERENCES public.app_users(id);

--
--
