"""Write a .env file from database values, with correct quoting/escaping.

Called by the installer so the generated .env round-trips any password (spaces,
'#', backslashes, quotes) through python-dotenv's double-quoted value rules.

Usage:
    python make_env.py <out_path> <host> <port> <name> <user> <password_file>
The password is read from a file (kept off the command line). Pass "" for none.
"""
from __future__ import annotations

import sys
from pathlib import Path


def _dq(value: str) -> str:
    """Return a python-dotenv double-quoted literal for an arbitrary string."""
    escaped = (
        value.replace("\\", "\\\\")
        .replace('"', '\\"')
        .replace("\n", "\\n")
        .replace("\r", "")
    )
    return f'"{escaped}"'


def main(argv: list[str]) -> int:
    if len(argv) < 6:
        print("usage: make_env.py <out> <host> <port> <name> <user> <password_file>",
              file=sys.stderr)
        return 2
    out_path, host, port, name, user = argv[0:5]
    pw_file = argv[5] if len(argv) > 5 else ""

    password = ""
    if pw_file:
        try:
            password = Path(pw_file).read_text(encoding="utf-8").rstrip("\r\n")
        except OSError:
            password = ""

    lines = [
        "# Generated by the KSA e-Invoice installer. Edit with care.",
        f"DB_NAME={name}",
        f"DB_USER={user}",
        f"DB_PASSWORD={_dq(password)}",
        f"DB_HOST={host}",
        f"DB_PORT={port}",
        "APP_ENV=production",
        "LOG_LEVEL=INFO",
        "",
    ]
    Path(out_path).write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv[1:]))
